export interface Candidates {
        careerLevel: string;
        currentposition: string;
        cvAttachment: string;
        degree: string;
        devexperience: string;
        email: string;
        englishSkills: string;
        examScore: string;
        expectedSalary: number;
        gpA1: number;
        gpA2: number;
        howdidyoufindus: string;
        id: number;
        interviewDate: string;
        joinDate: string;
        lastUdateLog: string;
        major: string;
        name: string;
        nationality: string;
        noteLog: string;
        otherUniversity: string;
        phoneNumber: string;
        status: string;
        teamLeaderExperience: string;
        technologies: Date;
        toCallDate: Date;
        university: string;
}
