export interface Candidates {
        id: number;
        name: string;
        phoneNumber: string;
        email: string;
        careerLevel: string;
        currentPosition: string;
        degree: string;
        devExperience: string;
        teamLeaderExperience: string;
        englishSkills: string;
        examScore: string;
        expectedSalary: number;
        gpA1: number;
        gpA2: number;
        howDidYouFindUs: string;
        major: string;
        nationality: string;
        otherUniversity: string;
        status: string;
        technologies: Date;
        toCallDate: Date;
        university: string;
        interviewDate: string;
        joinDate: string;
        lastUdateLog: string;
        cvAttachment: string;
        notes: string;
}
